name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.7'
          - '3.4.2'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        env:
          LIGHTSPARK_TEST_API_TOKEN_CLIENT_ID: ${{ secrets.LIGHTSPARK_TEST_API_TOKEN_CLIENT_ID }}
          LIGHTSPARK_TEST_API_TOKEN_CLIENT_SECRET: ${{ secrets.LIGHTSPARK_TEST_API_TOKEN_CLIENT_SECRET }}
        run: bundle exec rake
